name = "smartproxy-iran"
main = "_worker.js"
compatibility_date = "2024-10-01"

[durable_objects]
bindings = [
  { name = "SMARTPROXY_DO", class_name = "SmartProxyDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["SmartProxyDO"]
